name: checkout-repo             #nama workflows
on: push                        #event push di repo
jobs: 
  checkout-repo-job:            #nama jobs
    runs-on: ubuntu-latest      #jalan di os ubuntu
    steps:                      #langkah - langkah agar tujuan job tercapai
      - name: "Install Git"
        run: sudo apt install -y git