name: checkout-repo             #nama workflows
on: push                        #event push di repo
jobs: 
  checkout-repo-job:            #nama jobs
    runs-on: ubuntu-latest      #jalan di os ubuntu
    steps:                      #langkah - langkah agar tujuan job tercapai
      # - name: "Install Git"
      #   run: sudo apt install -y git
      # - name: "Clone Repository"
      #   run: git clone https://github.com/docker-library/hello-world.git
      - uses: actions/checkout@v2
        with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: docker-library/hello-world
      - name: "List Directory"
        run: ls
      # - name: "Change Directory"
      #   run: cd hello-world/amd64/hello-world
      - name: "Run app"
        run: ./amd64/hello-world/hello